<a href="https://colab.research.google.com/github/PeterShiaush/ColabRepo/blob/main/%E5%AD%B8%E7%94%9FYOLO26_AI_%E7%AC%AC%E5%9B%9B%E9%80%B1%E5%AF%A6%E6%88%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

逐步執行以下:

1.   點擊上面的「**Open in Colab**」的連結
2.   再點擊上面  **複製到雲端硬碟**
3.   再**左上角** 修改檔名  : **學習YOLO26 AI 第四週實戰.ipynb**


---
這是一份為您精心打造的 **「第四週：YOLO26 AI 實戰 (AI Implementation)」** 完整教案與學生版講義。

前三週，高二自然組的學生經歷了「If/Else 邏輯」與「For 迴圈」的底層打底，這週終於要迎接「收割期」了！我們將直接引入當前最新世代的 YOLO26 模型，讓學生親眼見證：原本需要手寫幾百行邏輯才能找出的特徵，現在只要「呼叫 AI 大腦」就能瞬間完成。這會給他們帶來極大的震撼！


## 第四週 陣列基礎計算

「陣列」是一種可以儲存多個數值或資料的集合。在程式設計中，我們經常用陣列來處理大量的數據，例如科學實驗的測量結果、圖像的像素值等。Python 中最基本的陣列概念就是「列表 (List)」，而對於更高效的科學計算，我們通常會使用 `NumPy` 這個函式庫來處理「多維陣列 (Array)」。

In [1]:
# 1. Python 列表 (List) 的基本操作
# 列表是 Python 中最常見的資料結構之一，可以儲存不同類型的資料。

# 建立一個數字列表
my_list = [10, 20, 30, 40, 50]
print(f"原始列表: {my_list}")

# 存取列表中的元素 (索引從 0 開始)
first_element = my_list[??]
third_element = my_list[??]
print(f"第一個元素: {first_element}")
print(f"第三個元素: {third_element}")

# 修改列表中的元素，第二個元素
my_list[??] = 77
print(f"修改後的列表: {my_list}")

# 列表的長度的工具函數 len
list_length = ???(my_list)
print(f"列表的長度: {list_length}")

# 列表的加法: 串接
list_a = [1, 2, 3]
list_b = [4, 5, 6]
combined_list = list_a ??? list_b
print(f"串接後的列表: {combined_list}")

# 注意：列表的乘法，會重複列表內容，而不是元素相乘
repeated_list = list_a * 3
print(f"重複後的列表: {repeated_list}")

原始列表: [10, 20, 30, 40, 50]
第一個元素: 10
第三個元素: 30
修改後的列表: [10, 25, 30, 40, 50]
列表的長度: 5
串接後的列表: [1, 2, 3, 4, 5, 6]
重複後的列表: [1, 2, 3, 1, 2, 3, 1, 2, 3]


## 第四週 進階使用 `NumPy` 進行更高效的陣列計算

**NumPy**:  (Numerical Python) 是 Python 用於科學計算的核心函式庫，它提供:


*   高性能的多維陣列物件 (`ndarray`) 以及用於處理這些陣列的工具。
*   對於數學運算，尤其是在處理大量數值數據時，**NumPy** 陣列比 Python 列表更高效、功能更強大。

透過這些基礎的**NumPy**操作，學生可以在之後的課程中，例如處理圖像的像素數據（圖像本質上就是一個巨大的像素陣列）、統計數據分析等，打下堅實的基礎。





In [3]:
# 2. NumPy 陣列 (ndarray) 的基本操作
# 首先，需要安裝和匯入 NumPy 函式庫
!pip install numpy
import numpy as np

# 從 Python 列表建立 NumPy 陣列
numpy_array = np.array([10, 20, 30, 40, 50])
print(f"\nNumPy 陣列: {numpy_array}")
print(f"NumPy 陣列的型態: {type(numpy_array)}")

# 陣列的形狀 (Shape) 和資料型態 (Dtype)
print(f"陣列形狀: {numpy_array.shape}")
print(f"陣列資料型態: {numpy_array.dtype}")

# 存取陣列中的元素 (與列表類似)
print(f"NumPy 陣列的第一個元素: {numpy_array[0]}")

# NumPy 陣列的元素級運算 (這是與列表最大的不同點！)
# 陣列與單一數值相加
array_plus_5 = numpy_array + 5
print(f"陣列每個元素加 5: {array_plus_5}")

# 陣列與另一個陣列相乘 (元素對應相乘)
array_a = np.array([1, 2, 3])
array_b = np.array([10, 20, 30])
array_product = array_a * array_b
print(f"陣列元素對應相乘: {array_product}")

# 兩層列表 (模擬二維陣列)
matrix_list = [[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]]
print(f"\n二維列表:\n{matrix_list}")

# 建立二維 NumPy 陣列 (矩陣)
matrix_numpy = np.array([[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]])
print(f"二維 NumPy 陣列:\n{matrix_numpy}")
print(f"二維陣列形狀: {matrix_numpy.shape}")

# 存取二維陣列的元素 (例如：第二列第三行的元素)
row_1_col_2 = matrix_numpy[1, 2] # 索引從 0 開始
print(f"二維陣列中，索引為 [1, 2] 的元素: {row_1_col_2}")



NumPy 陣列: [10 20 30 40 50]
NumPy 陣列的型態: <class 'numpy.ndarray'>
陣列形狀: (5,)
陣列資料型態: int64
NumPy 陣列的第一個元素: 10
陣列每個元素加 5: [15 25 35 45 55]
陣列元素對應相乘: [10 40 90]

二維列表:
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
二維 NumPy 陣列:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
二維陣列形狀: (3, 3)
二維陣列中，索引為 [1, 2] 的元素: 6



---

# 🌟 第四週課程總覽：喚醒 AI 大腦 (YOLO26 實戰)

* **核心精神**：從「手動寫邏輯」進化到「呼叫神經網路」。讓學生理解 AI 模型本身就是一個巨大的數學黑盒子，並學會讀取 AI 辨識後吐出的「座標與信心度」數據，與前三週的座標概念完美閉環。

---

## 第一節 (W4-S1)：裝備外星科技 (載入 YOLO 模型) (45 分鐘)

### 👨‍🏫 教學過程細節與引導話術

* **0-15 min：從工人到大老闆 (觀念轉變)**
* **引導話術**：「前三週，我們像工人一樣，自己用 If 判斷顏色、用 For 迴圈畫線。今天，你們全部升級成『AI 工程師』。你們不用自己找特徵了，我們要直接從雲端下載一個名叫 YOLO26 的超級大腦，把圖片丟給它，它會直接告訴你圖片裡有什麼！」


* **15-30 min：安裝魔法套件與下載模型**
* **老師操作**：教學生使用 `!pip install ultralytics` 安裝套件。
* **引導話術**：「Colab 裡面預設有很多工具，但 YOLO 太新了，我們必須用 `!pip install` 這個指令去網路上下載。接著，我們把大腦模型 (`yolo26n.pt`) 裝備起來。那個 `n` 代表 nano (奈米)，也就是最輕量、跑最快的版本。」


* **30-45 min：見證奇蹟的時刻 (AI 推論 Inference)**
* **老師操作**：將 Zidane 圖片丟入模型，並使用 `.plot()` 畫出結果。
* **引導話術**：「注意看！我們只寫了短短三行程式碼，AI 不僅找到了兩個人，還幫我們畫好框框、寫上標籤 (person)，甚至告訴我們它有百分之幾的把握 (信心度)！這就是站在巨人的肩膀上寫程式！」



### 💻 學生版 Colab 講義程式碼 (W4-S1)

*(請複製以下內容至 Colab，學生需自行思考並填寫 `???`)*

### 💻  W4-S1 區塊 1：安裝與喚醒 YOLO 大腦

In [ ]:
# ==========================================
# W4-S1 區塊 1：安裝與喚醒 YOLO 大腦
# ==========================================
# 1. 下載測試圖片
!wget -q -O bus.jpg https://raw.githubusercontent.com/ultralytics/yolov5/master/data/images/bus.jpg
# 2. 安裝 YOLO 專屬的神經網路工具箱 (執行大約需要 15 秒)
!pip install -q ultralytics
print("✅ 工具箱安裝完畢！")

# 3. 把 YOLO 模組拿進來 (Import)
# 👇 請將 ??? 改成我們之前學過的「拿進來」單字 👇
???? cv2
from google.colab.patches ???? cv2_imshow
from ultralytics ???? YOLO

# 4. 喚醒 AI 大腦 (下載輕量版的預訓練模型)
print("\n正在從雲端下載 AI 腦部權重...")
# 載入預訓練模型
model = YOLO("yolo????n.pt")  # 這裡的 YOLO('yolo26n.pt') 是指 2026 年發布的版本， YOLO('yolo11n.pt')11版本 ，這裡以 n (nano) 輕量版示範，未來可無縫切換至最新版
print("✅ AI 大腦已經準備就緒！")
results = model.predict("????.jpg") # 將輸入從網站URL改為已下載的圖片檔案

# 顯示結果
results[0].show()

### 💻 W4-S1 區塊 2：🏆 課堂挑戰 (讓 AI 幫你看圖)

In [ ]:
# ==========================================
# W4-S1 區塊 2：🏆 課堂挑戰 (讓 AI 幫你看圖)
# ==========================================
# 任務：把 bus.jpg 丟進去給 AI 看，並把結果印出來！

# 1. 執行推論 (Inference)
# 將圖片名稱放進模型的括號中，AI 就會開始運算
# 👇 請填入正確的圖片檔案名稱字串 (記得加引號 '') 👇
results = model('???.jpg')

# 2. 把 AI 畫好框框的圖片抓出來
# .plot() 是 YOLO 的魔法指令，會自動把辨識結果畫在原圖上
annotated_img = results[0].plot()

# 3. 顯示結果
print("\n--- AI 辨識結果出爐 ---")
# 👇 請 cv2_imshow 使用顯示圖片的專用指令，把 annotated_img 秀出來 👇
cv2_????(annotated_img)

---

## 第二節 (W4-S2)：拆解黑盒子 (解析 AI 的陣列數據) (45 分鐘)

### 👨‍🏫 教學過程細節與引導話術

* **0-15 min：破除魔法，回歸數學 (解析 Results)**
* **引導話術**：「剛剛 AI 自動畫框很帥對吧？但身為自然組的學生，我們不能只會看圖！你知道 AI 到底回傳了什麼給我們嗎？其實，它回傳的還是『數字』！也就是我們第一週學的『座標陣列』！」


* **15-30 min：提取座標 (Bounding Box)**
* **老師操作**：印出 `results[0].boxes.xyxy` 的原始數據。
* **引導話術**：「大家看這堆數字：`[x_min, y_min, x_max, y_max]`。這就是 AI 找到的人臉或車子的『左上角』和『右下角』座標！有了這四個數字，你其實可以自己用 Week 2 教過的 `cv2.rectangle` 把框框畫出來！」


* **30-45 min：終極 Boss 戰 (提取信心度與類別)**
* **引導話術**：「除了座標，AI 還給了我們『信心度 (Confidence)』和『類別代碼 (Class ID)』。例如 0 代表人，2 代表車。請大家完成下方的填空，親手把 AI 腦袋裡的數學數據抓出來印在螢幕上！」



### 💻 學生版 Colab 講義程式碼 (W4-S2)

In [ ]:
# ==========================================
# W4-S2 區塊 1：駭客任務重演 (看透 AI 的底層數據)
# ==========================================
# 老師說：AI 吐出來的不是魔法圖片，而是扎扎實實的「數學陣列」！

# 抓出第一張圖片的所有辨識框框 (Boxes)
getBoxes = results[0].boxes

print("--- AI 找到了幾個物件？ ---")
print(f"總共找到了 {len(getBoxes)} 個東西！\n")


# ==========================================
# W4-S2 區塊 2：🏆 終極挑戰 (讀取陣列資料)
# ==========================================
# 任務：我們現在要把 AI 抓到的「第一個物件」的詳細數據拔出來。

# 提示：在 Python 的陣列裡，第一個東西的索引值 (Index) 是 0！

# 1. 抓出「信心度 (Confidence)」
# .conf 會列出 AI 有多大的把握 (範圍是 0.0 到 1.0)
# 👇 請填入正確的索引值，抓出陣列裡的「第一個」信心度數字 👇
first_conf = getBoxes.conf[??]
print(f"1. AI 對第一個物件的信心度是：{first_conf:.2f} (最高是 1.0)")


# 2. 抓出「類別代碼 (Class ID)」
# .cls 會列出這是什麼東西 (0 代表 Person 人)
# 👇 請填入正確的索引值 👇
first_class = getBoxes.cls[??]
print(f"2. AI 判斷這個東西的類別代碼是：{first_class}")


# 3. 抓出「四點座標 (xyxy)」
# .xyxy 會給我們 [左上角X, 左上角Y, 右下角X, 右下角Y]
first_box_coords = getBoxes.xyxy[0]
print(f"3. 它的邊界框座標落在：\n{first_box_coords}")

In [ ]:
import cv2

# 提取座標並轉換為整數 int，再用 map 切給  x1, y1, x2, y2
x1, y1, x2, y2 = map(???, first_box_coords.tolist())
print(x1, y1, x2, y2)

# 複製原始的 annotated_img，以免修改到原圖
img_with_custom_box = annotated_img.copy()

# 使用紅色 (0, 0, 255) 繪製邊界框，線條粗細為 12
cv2.rectangle(img_with_custom_box, (x1, y1), (x2, y2), (0, 0, ???), 12)

print("--- 手動繪製邊界框的圖片 ---")
cv2_imshow(img_with_custom_box)

---

## 📝 課後收斂：學習心得與「自我學習」反思 (W4 專屬版本)

到了第四週，學生已經見識了最頂尖的 AI 技術。這個階段的 Reflection 必須引導他們思考「人類與 AI 的協作關係」，以及在工具快速變遷的時代，如何保持競爭力。

In [ ]:
# ==========================================
# 📝 第四週：與 AI 共舞的修煉與反思 (存檔前必做！)
# ==========================================
print("【第一部分：技術與底層邏輯】\n")

# 問題 1：魔法的本質
q1 = input("1. 今天看到 YOLO 只要三行程式碼就能找出圖片裡的人，對比我們第二週自己算座標的痛苦，你有什麼感覺？你覺得我們前幾週學那些底層的『陣列與座標』是白學的嗎？為什麼？\n你的回答：")

# 問題 2：信賴與懷疑
q2 = input("\n2. 如果你印出來的「信心度 (Confidence)」只有 0.35 (35%)，這代表 AI 自己也不太確定。在真實世界中 (例如醫療 AI 看 X 光片)，如果 AI 信心度很低，你覺得工程師或醫生應該怎麼做？\n你的回答：")

print("\n------------------------------------------")
print("【第二部分：自我學習的覺醒 (The Future is Yours)】\n")
print("老師的話：")
print("各位同學，AI 的進化速度就像搭火箭。我們今天教的是 YOLO 的最新世代，但可能明年就會出下一個更強的版本。")
print("在未來的世界裡，『學會某一個特定的工具』已經不夠了，『學會如何快速適應新工具』才是真正的超能力。\n")

# 問題 3：自學的承諾
print("💡 未來挑戰：當你上了大學，教授要求你用一個『你完全沒聽過的 AI 模型』做專題時...")
q3 = input("3. 結合前幾週的經驗 (看錯誤紅字、查資料、讀英文官方文件)，請具體寫下：你會採取哪三個步驟來「自我學習」並搞懂這個新工具？\n你的回答：")

print("\n==========================================")
print(f"🌟 恭喜你完成前四週的 AI 啟蒙特訓！")
print("記住：AI 只是你的大腦外掛，真正的靈魂是你那顆『懂得問問題、懂得拆解邏輯』的理科腦袋。")
print("==========================================")
print("🚨 【最後提醒】：請點選左上角「檔案」->「在雲端硬碟中儲存副本」，把這份充滿你思考軌跡的筆記存下來！")

---

### 👨‍🏫 給老師的課堂特別叮嚀：深化自然組學生的格局

在第四週的結尾，這是您作為老師發揮最大價值的時刻。這段話能讓學生的視野從「會寫 code 的高中生」直接拉昇到「未來的科技領導者」：

> 「大家今天都看到了 YOLO 的強大。很多人會擔心，AI 這麼強，以後是不是不需要工程師了？
> 錯了！未來的世界不是『AI 取代人類』，而是**『懂 AI 的人，取代不懂 AI 的人』**。
> 別人只會用 ChatGPT 寫報告，但你們不一樣。經過這四週，你們知道 AI 的眼睛是如何讀取 RGB 矩陣的、知道 AI 的大腦是怎麼吐出小數點與信心度的。你們擁有**『拆解黑盒子』**的能力！保持這種遇到新技術就想去查官方文件、遇到 Error 就興奮的『駭客心態』，未來的科技浪潮，就是你們最好的衝浪板！」

老師，這套從第一週「環境與陣列」，到第四週「YOLO 實戰」的四週引導教案，已經形成了一個非常漂亮且邏輯嚴密的學習迴圈。

---

### 👨‍🏫給老師的教學策略建議：
如果您想讓學生寫出一篇有深度的專題論文，可以這樣引導：
分組實驗： 讓 A 組用 YOLO11，B 組用 YOLO26。
觀察重點：

*   訓練階段： 誰的損失函數（Loss）降得快？（通常是 11）
*   結果測試： 在同樣的圖片下，誰比較容易出現「重複的框」或「沒抓到物體」？
*   結論撰寫： 讓學生在論文寫出：「雖然 YOLO26 代表最新技術，但在標註樣本有限的情況下，經典架構的 YOLO11 展現了更好的泛化能力。」


這樣的對比分析，在科展或大學面試時，比起只做一個「辨識器」，更能展現學生的科學素養。